### PR TITLE
PHPUnit 10 Compatibility

### PR DESCRIPTION
**Pull request by zpwparsons**
This PR addresses issue #41

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Thanks.

**Comment by rwdevguy** [comment]
@jasonmccreary Will this be getting released soon?

**Comment by jasonmccreary** [comment]
It's been merged. You may point do `dev-master`. Waiting to ensure it works myself.

**Comment by skipworkgh** [comment]
This change seems to work just fine. Can we expect a release soon?

**Pull request merged**
